# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5441c048ead9aa7a257d1a3035167a68e699ea0d469caf70d23fd7de63ee18bbd396bd19317972f28d9ef5303b959625bbdd2042830969864cc00cda9f210294

test:
  secret_key_base: b2330ec2a36661a9832a29eb5e4d222dd25147897e4c6d6f3547a837529206b8c10c6cf1cd93a2d05aeedece5ee54247870352c165640ddb2b29e5d1cae6317c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
